spring:
 profiles:
  active: dev
 application:
  name: people-api
 jpa:
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  hibernate:
    ddl-auto: none
 flyway:
    locations: classpath:db/migration/postgres
    
---

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: SpringBootKeycloak
  resource: login-app
  public-client: false
  principal-attribute: preferred_username
  credentials:
    secret: de75a90f-5b07-471a-9dbf-6f1d5e406c92

---
spring:
 profiles: dev
 datasource:
    url: jdbc:postgresql://localhost:5432/peopleapi
    username: peopleapi
    password: peopleapi
    
---

spring:
    profiles: prod
    datasource:
        jndi-name: java:comp/env/jdbc/peopleapi