spring:
 profiles:
  active: dev
 application:
  name: people-api
 jpa:
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  hibernate:
    ddl-auto: none
 flyway:
    locations: classpath:db/migration/postgres
    
---

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: SpringBootKeycloak
  resource: login-app
  public-client: false
  principal-attribute: preferred_username
  credentials:
    secret: fb1c549a-5609-4c2c-9ae7-1a0999d50635

---
spring:
 profiles: dev
 datasource:
    url: jdbc:postgresql://localhost:5432/peopleapi
    username: peopleapi
    password: peopleapi
    
---

spring:
 profiles: prod
 datasource:
    url: jdbc:postgresql://postgresapi:5432/peopleapi
    username: peopleapi
    password: peopleapi
    # jndi-name: java:comp/env/jdbc/peopleapi
        
        