spring:
 profiles:
  active: dev
 application:
  name: people-api
 jpa:
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  hibernate:
    ddl-auto: none
 flyway:
    locations: classpath:db/migration/postgres
    
---

security:
 oauth:
  enabled: true
  server:
    url: http://localhost:8888/sso/oauth/url_check_token
    token: http://localhost:8888/sso/oauth/token
    clientId: peopleapi
    clientSecret: peopleapi
    
---

spring:
 profiles: dev
 datasource:
    url: jdbc:postgresql://localhost:5432/peopleapi
    username: peopleapi
    password: peopleapi
---
spring:
    profiles: prod
    datasource:
        jndi-name: java:comp/env/jdbc/peopleapi